import randumb from 'no-duplicates';

const teamNames = [
  '🐻THE BEARS🐻',
  '🐼THE PANDAS🐼',
  '🐨THE KOALAS🐨',
  '🦆THE DUCKS🦆',
  '🐵THE MONKEYS🐵',
  '🦁THE LIONS🦁',
  '🐮THE COWS🐮',
  '🦊THE FOXES🦊',
  '🐰THE RABBITS🐰',
  '🐭THE MICE🐭',
  '🐹THE HAMSTERS🐹',
  '🐶THE DOGS🐶',
  '🐔THE CHICKENS🐔',
  '🐧THE PENGUINS🐧',
  '🦅THE EAGLES🦅',
  '🦄THE UNICORNS🦄',
  '🐴THE HORSES🐴',
  '🦖THE DINOSAURS🦖',
  '🐢THE TURTLES🐢',
  '🐜THE ANTS🐜',
  '🐌THE SNAILS🐌 ',
  '🦓THE ZEBRAS🦓',
  '🦍THE GORILLAS🦍',
  '🐪THE CAMELS🐪',
  '🐱THE CATS🐱',
  '🐷THE PIGS🐷',
  '🦛THE HIPPOS🦛',
  '🐘THE ELEPHANTS🐘',
  '🦈THE SHARKS🦈',
  '🐳THE WHALES🐳',
  '🦑THE SQUIDS🦑',
  '🦘THE KANGAROOS🦘',
  '🦨THE SKUNKS🦨',
  '🦒THE GIRAFFES🦒',
  '🦥THE SLOTHS🦥',
  '🐸THE FROGS🐸',
  '🐅THE TIGERS🐅',
  '🦧THE ORANGUTANS🦧',
  '🐑THE SHEEP🐑',
  '🦌THE DEER🦌',
  '🎅🏻THE SANTAS🎅🏻',
  '🧚🏻‍♀️THE FAIRIES🧚🏻‍♀️',
  '🐞THE LADY BUGS🐞',
  '🐺THE WOLVES🐺',
  '🦇THE BATS🦇',
  '🐿THE SQUIRRELS🐿',
  '🥞THE PANCAKES🥞',
  '🍓THE STRAWBERRIES🍓',
  '🍎THE APPLES🍎',
  '👻THE GHOSTS👻',
  '🤖THE ROBOTS🤖',
  '🎃THE PUMPKINS🎃',
  '🧟‍♀️THE ZOMBIES🧟‍♀️'
];
const ranNames = randumb(teamNames);
export default function getTeamName() {
  return ranNames();
}
